name: aexgym
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - pandas 
  - pytorch
  - scikit-learn
  - statsmodels
  - tqdm
  - hydra-core
  - omegaconf
  - pip:
      - --no-deps
      - -e .
